version: '3.7'
services:
  jenkins:
    container_name: jenkins_docker
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - btreProd_net
  web:
    container_name: web_docker
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn try_django.wsgi:application --bind 0.0.0.0:8000
    networks:
      - btreProd_net
    tty: true
    expose:
      - 8000
    depends_on:
      - db
  db:
    container_name: db_docker
    networks:
      - btreProd_net
    ports:
      - 5432:5432
    tty: true
    image: postgres:12.0-alpine
    environment:
      POSTGRES_PASSWORD: password1234
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  nginx:
    container_name: nginx_docker
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/hbihub.com/fullchain.pem:/etc/letsencrypt/live/hbihub.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/hbihub.com/privkey.pem:/etc/letsencrypt/live/hbihub.com/privkey.pem
    networks:
      - btreProd_net
    depends_on:
      - web

networks:
  btreProd_net:
